fix: don't pass nodes that don't have `database` attribute to build_catalog relation (#1170)
### Description
Follow on to: https://github.com/databricks/dbt-databricks/pull/1164

core will sometimes pass an Export object to `__generate_database_name`,
Export objects are _kind of_ like nodes but are not.

This causes an exception like:
```
  File "/venv/dbt-latest/lib/python3.11/site-packages/dbt/adapters/databricks/catalogs/_unity.py", line 41, in build_relation
    else model.database,
         ^^^^^^^^^^^^^^
AttributeError: 'Export' object has no attribute 'database'
```

I've done some manual testing to validate this doesn't cause an issue

<!---
Include the number of the issue addressed by this PR above if
applicable.

  Example:
    resolves #1234

Please review our pull request review process in CONTRIBUTING.md before
your proceed.
-->



<!--- Describe the Pull Request here -->

### Checklist

- [x] I have run this code in development and it appears to resolve the
stated issue
- [x] This PR includes tests, or tests are not required/relevant for
this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my
change to the "dbt-databricks next" section.