Fix linter errors. (#263)
### Description

Fixes linter errors caused by the upstream changes https://github.com/dbt-labs/dbt-core/commit/17014bfad3e204279c94c6a0285f784fc10711eb.

```
dbt/adapters/databricks/impl.py:144: error: "AttrDict" has no attribute "select"  [attr-defined]
dbt/adapters/databricks/impl.py:163: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "AttrDict")  [assignment]
dbt/adapters/databricks/impl.py:167: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "AttrDict")  [assignment]
dbt/adapters/databricks/impl.py:214: error: "AttrDict" has no attribute "columns"  [attr-defined]
dbt/adapters/databricks/impl.py:290: error: Argument 2 to "parse_describe_extended" of "DatabricksAdapter" has incompatible type "AttrDict"; expected "List[Any]"  [arg-type]
Found 5 errors in 1 file (checked 49 source files)
```