fix: add check in _get to validate model had gettable config (#1164)
<!-- Please review our pull request review process in CONTRIBUTING.md
before your proceed. -->

We're seeing errors when folks run with dbt-databricks + leveraging
saved queries:
```
2025-08-23 04:50:36.898349 (MainThread): 04:50:36  Encountered an error:
'ExportConfig' object has no attribute 'get'
```
The issue here is that core uses the get_database_name macro for
non-model nodes some of which have "config" attributes that are not the
expected type.

<!---
Include the number of the issue addressed by this PR above if
applicable.

  Example:
    resolves #1234

Please review our pull request review process in CONTRIBUTING.md before
your proceed.
-->

### Description

<!--- Describe the Pull Request here -->

### Checklist

- [ ] I have run this code in development and it appears to resolve the
stated issue
- [ ] This PR includes tests, or tests are not required/relevant for
this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my
change to the "dbt-databricks next" section.